  export const userData = [
  {
    name: 'Jan',
    "Active User": 4000,
  },
  {
    name: 'Feb',
    "Active User": 3000,
  },
  {
    name: 'Mar',
    "Active User": 5000,
  },
  {
    name: 'Apr',
    "Active User": 2780,
  },
  {
    name: 'May',
    "Active User": 1890,
  },
  {
    name: 'Jun',
    "Active User": 4000,
  },
  {
    name: 'Jul',
    "Active User": 6000,
  },
  {
    name: 'Aug',
    "Active User": 3000,
  },
  {
    name: 'Sep',
    "Active User": 2000,
  },
  {
    name: 'Oct',
    "Active User": 3780,
  },
  {
    name: 'Nov',
    "Active User": 1890,
  },
  {
    name: 'Dec',
    "Active User": 2390,
  },
];

export const userRows = [
{  id: 1,
   username: 'Aurelio Martinez',
   firstName: 'Aurelio',
   avator: "https://randomuser.me/api/portraits/men/52.jpg",
   email: "martinez@example.com",
   status: "active",
   transcation: "$120.00",
},
{  id: 2,
   username: 'Aurelio Martinez',
   firstName: 'Aurelio',
   avator: "https://randomuser.me/api/portraits/men/52.jpg",
   email: "martinez@example.com",
   status: "active",
   transcation: "$120.00",
},
{  id: 3,
   username: 'Aurelio Martinez',
   firstName: 'Aurelio',
   avator: "https://randomuser.me/api/portraits/men/52.jpg",
   email: "martinez@example.com",
   status: "active",
   transcation: "$120.00",
},
{  id: 4,
   username: 'Aurelio Martinez',
   firstName: 'Aurelio',
   avator: "https://randomuser.me/api/portraits/men/52.jpg",
   email: "martinez@example.com",
   status: "active",
   transcation: "$120.00",
},
{  id: 5,
   username: 'Aurelio Martinez',
   firstName: 'Aurelio',
   avator: "https://randomuser.me/api/portraits/men/52.jpg",
   email: "martinez@example.com",
   status: "active",
   transcation: "$120.00",
},
{  id: 6,
   username: 'Aurelio Martinez',
   firstName: 'Aurelio',
   avator: "https://randomuser.me/api/portraits/men/52.jpg",
   email: "martinez@example.com",
   status: "active",
   transcation: "$120.00",
},
{  id: 7,
   username: 'Aurelio Martinez',
   firstName: 'Aurelio',
   avator: "https://randomuser.me/api/portraits/men/52.jpg",
   email: "martinez@example.com",
   status: "active",
   transcation: "$120.00",
},
{  id: 8,
   username: 'Aurelio Martinez',
   firstName: 'Aurelio',
   avator: "https://randomuser.me/api/portraits/men/52.jpg",
   email: "martinez@example.com",
   status: "active",
   transcation: "$120.00",
},
{  id: 9,
   username: 'Aurelio Martinez',
   firstName: 'Aurelio',
   avator: "https://randomuser.me/api/portraits/men/52.jpg",
   email: "martinez@example.com",
   status: "active",
   transcation: "$120.00",
},
{  id: 10,
   username: 'Aurelio Martinez',
   firstName: 'Aurelio',
   avator: "https://randomuser.me/api/portraits/men/52.jpg",
   email: "martinez@example.com",
   status: "active",
   transcation: "$120.00",
},
];
